Refactoring Usage Simulation + Abortion
PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core pull request #77
Opened 2024-05-23 11:23 UTC by klinakuf

- updating context for user abortion
- fix caller in child context creation.
- delete useless comments, delete useless setting of callers.
- add some assertions, extends doc
- fix infracalls.
- remove unused operation
- fix stack for extcall and entry level sys call.
- fix stack handling to accomodate infrastructure calls.
- introducing UserProgressed event
- deleted userprogressed and palladio formating
- bug fix when initiating a new closed workload user
- formatting

2024-06-03 07:26 UTC, stiesssh reviewed
- ran it on RMCU, got results. 
  * checked, that stack is empty after each normal request. 
  * did not check state of stack in case of abortion, as i don't know how to trigger abortion (deterministically)
 - changes appear to be reasonable.
 
 as already mentioned in person, i dislike creating new users in case of abortion with closed workload, but i also undestand, that it is difficult to solve in any other way right now, thus i shall not hinder the merging of this PR. But, i want a follow up issue, to takle that problem. maybe we even need to rethink how to identify probes.

2024-06-03 07:26 UTC, stiesssh commented on org.palladiosimulator.analyzer.slingshot.behavior.usagesimulation.data/src/org/palladiosimulator/analyzer/slingshot/behavior/usagemodel/entities/interpretationcontext/UserInterpretationContext.java
this is where you removed the parent, right? then add yourself to the authors :D

2024-06-03 08:06 UTC, stiesssh requested changes
please merge `master` into this branch, i keep getting an assertion-error.

2024-06-18 08:47 UTC, klinakuf commented
Is this the issue you wanted to have https://github.com/PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core/issues/78

2024-06-21 07:15 UTC, stiesssh commented
I tested with a more complicated UsageModel, that contains loops and branches: 

![image](https://github.com/PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core/assets/44230629/2731c3e8-4c9a-436c-be25-8c213d23d317)
 
* I meassure *state of active resource*.
* Expectation: 4 times state = 1 $\rightarrow$ state = 0 for three seconds  $\rightarrow$ 4 times state = 1  $\rightarrow$ ...

* Reality: 
![image](https://github.com/PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core/assets/44230629/6cb9be54-38e8-4201-8a05-ee1291ef1bac)

* Problem: Loops are broken. I tried different numbers of loop iterations, but the loop body always get executed only once.
* I'm not sure whether this Problem was caused by this PR, or whether it existed before. please check and either fix it (if related to this PR) or create a new issue (if not related to this PR).

2024-06-21 07:16 UTC, stiesssh reviewed
see comment.

2024-07-03 08:42 UTC, stiesssh requested changes
I keep getting problems with the preview feature you used. 
In the end i think it is cumbersome to adapt the IDE and the runconfig, especially if we get some student to work on it. 

Thus, i suggest to go back to default java 17 features.

2024-07-03 14:37 UTC, stiesssh requested changes
Now it's doing one iteration to much.

Or do i misunderstand the loop count? Cause i assume, that loop count = n means that, the loop body should be executed n-times, how ever now it get's executed n+1 times.

EDIT: to make sure, i executed the same model with SimuLizar, and the results are indeed different: 
**SimuLizar** (always 4 calls):
![image](https://github.com/PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core/assets/44230629/ba3ecb3f-35b4-4515-8fcb-54e3ec6add9e)


**Slingshot** (4 or 5 calls):
![image](https://github.com/PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core/assets/44230629/2cadc3bc-65ff-4902-b635-78674beadd46)

2024-07-04 09:32 UTC, stiesssh approved these changes
It works now.

Don't know what caused the problem before, probably some updated problems inside eclipse.

2024-07-04 09:33 UTC, merged